
# H3.6M Training Config
train:
  epochs: 50
  batch_size: 32
  batch_size_test: 32
  lr: 2.0e-4
  valid_epoch_interval: 1

data:
  dataset: "h36m"
  data_dir: "/home/allen/datasets"
  h36m_protocol: "deposit"
  input_n: 10              
  output_n: 10       
  skip_rate: 1 
  split: 0
  joints: 22
  downsample: 2
  miss_type: "no_miss"
  miss_rate: 0.2
  no_overlap: false # 切窗可不可以重疊
  all_data: true
  data_ratio: 1.0
  pad_short_sequences: false # 要不要對長度不足的 data 做 padding
  output_dir: "runs/base_h36m_10_10" # 模型權重和訓練日誌的輸出路徑

diffusion:
  beta_end: 0.5
  beta_start: 0.0001
  channels: 64
  diffusion_embedding_dim: 128
  layers: 12
  nheads: 8
  num_steps: 50
  schedule: cosine
  moe: False

model:
  balance_loss: False
  balance_loss_weight: 0.01
  multirouter: false
  featureemb: 16
  is_unconditional: 0
  text_encoder: sentence-transformer
  text_mode: cross_attn
  textemb: 384
  timeemb: 128
  use_r3: False

text_injection:
  decouple_spatial_temporal: false
  use_clip_encoder: false
  use_deep_text_projector: false
  use_late_injection: false
  use_time_aware_film: false

# Other legacy settings
grad_clip: 1.0
